### ISSUE TITLE
ephemeris

### ISSUE THREAD

**Issue by t0in4** [dcf21/astrolabe#1]
Hello, 
awsome project!
I have a question not directly related to astrolabe. 
Maybe, you know - how to calculate ephemeris from scratch. I am from 62 latitude and i suppose, that ready-to-use online ephemeris are not suitable. 
Best regards, Eyehail

**Comment by dcf21** [comment]
Hi,

It sounds like you're after another tool that I've written: https://github.com/dcf21/ephemeris-compute-de430

That can compute an ephemeris from scratch, either using NASA's DE430 data files, or using orbital elements (only accurate to around 1 arcminute).

If you want to learn the math behind it, a good starting point in Jean Meeus's _Astronomical Algorithms_ or if you really want gory detail, the _Explanatory Supplement to the Astronomical Almanac_. Be warned, though - neither of these books are light reading!

Cheers,

Dominic
